config/routes.rb
Rails.application.routes.draw do
  post 'add_to_cart' => 'cart#add_to_cart'

  get 'cart/view_order'
  get 'view_order' => "cart#view_order"
  get 'cart/checkout'
  get 'checkout' => 'cart#checkout'

  get 'storefront/all_items'
  get 'storefront/items_by_brand'
  get 'storefront/items_by_category'
  
  get 'items_by_category' => 'storefront#items_by_category'
  get 'items_by_brand' => 'storefront#items_by_brand'

  devise_for :users
  resources :products
  root 'storefront#all_items'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
      can :manage, Product
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
end

app/models/line_item.rb
class LineItem < ApplicationRecord
	belongs_to :order, optional: true
	belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	has_many :line_items
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category

	mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :encryptable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders

  def admin?
  	role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :set_categories_and_brands

  before_action :configure_permitted_parameters, if: :devise_controller?

  def set_categories_and_brands
    @categories = Category.all
    @brands = Product.pluck(:brand).sort.uniq
    @category_names_and_ids = @categories.collect do |category|
      [category.name, category.id]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:role])
    devise_parameter_sanitizer.permit(:account_update, keys: [:role])
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def add_to_cart
  	line_item = LineItem.create(
  		product_id: params[:product_id],
  		quantity: params[:quantity]
  	)
  	line_item.update(line_item_total: (line_item.quantity * line_item.product.price))

  	redirect_back(fallback_location: root_path)
  end

  def view_order
  	@line_items = LineItem.all
  end

  def checkout
  	line_items = LineItem.all
  	@order = Order.create(
  		user_id: current_user.id,
  		line_items: line_items,
  		subtotal: 0
  	)
  	line_items.each do |line_item|

  		if line_item.quantity.present?
	  		product = line_item.product
	  		new_quantity = product.quantity - line_item.quantity
	  		product.update(quantity: new_quantity)
  		end
  		@order.subtotal += line_item.line_item_total
  	end
  	@order.update(sales_tax: (@order.subtotal * 0.0575))
  	@order.update(total: (@order.sales_tax + @order.subtotal))
  	@order.save
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
    def new
    @product = Product.new
    end

  # GET /products/1/edit
    def edit
  
    end
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :quantity, :description, :brand, :rating, :category_id, :image)
    end

    

app/controllers/storefront_controller.rb
class StorefrontController < ApplicationController
  def all_items
  	@products = Product.all
  end

  def items_by_category
  	@category = Category.find(params[:category_id])
  end

  def items_by_brand
  	@brand = params[:brand]
  	@products = Product.where(brand: @brand)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/storefront_helper.rb
module StorefrontHelper
end

app/views/cart/add_to_cart.html.erb
<h1>Cart#add_to_cart</h1>
<p>Find me in app/views/cart/add_to_cart.html.erb</p>

app/views/cart/checkout.html.erb
<h1>Cart#checkout</h1>
<p>Find me in app/views/cart/checkout.html.erb</p>

app/views/cart/view_order.html.erb
<h2>My Cart</h2>

<table class="table">
	<thead>
		<tr>
			<th>Product name</th>
			<th>Qty</th>
			<th>Price</th>
			<th>Total Price</th>
		  </tr>
	</thead>
    <tbody>
	  <% @line_items.each do |line_item| %>
	  	<tr>
			<td><%= line_item.product.name %></td>
			<td><%=  line_item.quantity %></td>
			<td><%= number_to_currency line_item.product.price %></td>
			<td><%= number_to_currency line_item.line_item_total %></td>
			</tr>
		<% end %>
    </tbody>
</table>

<div>
	<%= link_to "Proceed to checkout??", checkout_path, class: "btn btn-success" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TTS E-Commerce</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
      <% if user_signed_in? %>
        <nav class="navbar ">
           <div class="collapse navbar-collapse">
               <div class="navbar-nav pull-left">
                <%= link_to "View Cart", view_order_path %>
               </div>
               <div class="navbar-nav pull-right">
                 <span class="nav-item"><%= current_user.email %></span>
                 <%= link_to "Edit Profile", edit_user_registration_path, class: 'nav-item nav-link' %>
                 <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: ' nav-item nav-link' %>
               </div>
             
           </div>
        </nav>
        <div class = "row">
          <div class="col-sm-6 col-md-6">
            <h4>Categories</h4>
            <ul>
              <% @categories.each do |category| %>
                <li><%= link_to category.name, items_by_category_path(category_id: category.id) %></li>
              <% end %>   
            </ul>
          </div>
          <div class="col-sm-6 col-md-6">
            <h4>Brands</h4>
            <ul>
              <% @brands.each do |brand| %>
                <li><%= link_to brand, items_by_brand_path(brand: brand) %></li>
              <% end %>   
            </ul>
          </div>
        </div>
      <% end %>
    	<%= yield %>
	</div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%=form.file_field :image %>
  </div>


  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :product_price %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, id: :product_quantity %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :product_description %>
  </div>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand, id: :product_brand %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating, id: :product_rating %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.select :category_id, @category_names_and_ids, {include_blank: "Please select a value"}%>
    
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Description</th>
      <th>Brand</th>
      <th>Rating</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.quantity %></td>
        <td><%= product.description %></td>
        <td><%= product.brand %></td>
        <td><%= product.rating %></td>
        <td><%= product.category.name %></td>
        <td><%= link_to 'Show', product %></td>
        <% if can? :update, product %>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
          <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :create, Product %>
  <%= link_to 'New Product', new_product_path %>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <% if @product.image.present? %>
  <%= image_tag @product.image.url, size: "175" %>
  <%end %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @product.rating %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category.name %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/storefront/_list_products.html.erb
<div class="row">
  <% products.each do |product| %>
    <div class="col-md-4">
      <div class="well center-it">
        <% if product.image.present? %>
        	<p><%= image_tag product.image.url, size: "100" %></p>
    	  <% end %>
        <h3><%= link_to product.name, product %></h3>
        <p><%= number_to_currency product.price %></p>
        <p>
          <a href='#' data-toggle="modal" data-target="#myModal_<%= product.id %>">
            <span class='glyphicon glyphicon-plus'></span>More Info
          </a>
        </p>

        <%= form_tag add_to_cart_path do %>
          <%= hidden_field_tag :product_id, product.id %>
          <%= number_field_tag :quantity, 0, placeholder: "How many do you want"%>
          <%= submit_tag "Add to Cart", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/storefront/all_items.html.erb
<h1>Welcome to Tech Talent Store</h1>
<p>Give us your money!</p>
<%= render 'list_products', products: @products %>

app/views/storefront/items_by_brand.html.erb
<h1><%= @brand %></h1>
<%= render 'list_products', products: @products %>

app/views/storefront/items_by_category.html.erb
<h1><%= @category.name %></h1>
<%= render 'list_products', products: @category.products %>